apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: xebikart-dashboard
spec:
  selector:
    matchLabels:
      app: xebikart
      tier: dashboard
  replicas: 3
  template:
    metadata:
      labels:
        app: xebikart
        tier: dashboard
    spec:
      containers:
      - name: nginx-react
        image: eu.gcr.io/xebikart-dev-1/xebikart-dashboard:latest
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        ports:
        - containerPort: 80
