version: 2
jobs:
  "Build":
    docker:
      - image: circleci/node:10.15.2

    working_directory: ~/xebikart

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: yarn build

workflows:
  version: 2
  full:
    jobs:
      - "Build"
