version: 2.1
orbs:
  gcp-gcr: circleci/gcp-gcr@0.0.4

jobs:
  "Build":
    docker:
      - image: circleci/node:11.14.0

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn build

  "Build Docker image":
    docker:
      - image: circleci/node:11.14.0
    steps:
      - gcp-gcr/build-image:
          image: xebikart-dashboard
          tag: latest
          path-to-dockerfile: Dockerfile.clean
          registry-url: eu.gcr.io

workflows:
  version: 2
  full:
    jobs:
      - "Build"
      - "Build Docker image":
          requires:
            - "Build"
