version: 2.1
orbs:
  gcp-gcr: circleci/gcp-gcr@0.0.4
  gcp-cli: circleci/gcp-cli@1.3.0

jobs:
  "Build":
    docker:
      - image: circleci/node:11.14.0

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn build

  "Login to GCP":
    executor: google
    steps:
      - gcp-cli/initialize

  # Image is built with the CircleCI gcp-gcr Orb
  # https://circleci.com/orbs/registry/orb/circleci/gcp-gcr
  # This is essentially just a convenient wrapper around `docker build`
  "Build Docker image":
    machine:
      docker_layer_caching: true
    steps:
      - checkout
      - gcp-gcr/build-image:
          image: xebikart-dashboard
          tag: latest
          registry-url: eu.gcr.io
      - run:
          name: Export Docker image so it can be persisted to workspace
          command: |
            mkdir docker-images/
            docker save --output docker-images/xebikart-dashboard.tar eu.gcr.io/${GOOGLE_PROJECT_ID}/xebikart-dashboard:latest
      - persist_to_workspace:
          root: .
          paths:
            - docker-images/xebikart-dashboard.tar

  # Image is pushed to GCR with the CircleCI gcp-gcr Orb
  # https://circleci.com/orbs/registry/orb/circleci/gcp-gcr
  # This is essentially just a convenient wrapper around `docker push`
  "Push Docker image to GCR":
    machine:
      docker_layer_caching: true
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Load Docker image from workspace
          command: docker load --input docker-images/xebikart-dashboard.tar
      - gcp-gcr/push-image:
          image: xebikart-dashboard
          tag: latest
          registry-url: eu.gcr.io

workflows:
  version: 2
  full:
    jobs:
      - "Build"
      - "Build Docker image":
          context: "XebiKart - GCP/GKE Deployment"
          requires:
            - "Build"
      - "Login to GCP":
          context: "XebiKart - GCP/GKE Deployment"
      - "Push Docker image to GCR":
          context: "XebiKart - GCP/GKE Deployment"
          requires:
            - "Build Docker image"
            - "Login to GCP"
